# Generated by Django 3.2.9 on 2021-11-26 22:09

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('descripcion', models.TextField(max_length=300)),
                ('photo', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('meta_titulo', models.CharField(blank=True, max_length=60, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images')),
                ('resumen', models.TextField(max_length=200)),
                ('meta_description', models.CharField(blank=True, max_length=155, null=True)),
                ('texto', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('publicado', models.BooleanField(default=False)),
                ('slug', models.SlugField(unique=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.autor')),
                ('tags', models.ManyToManyField(blank=True, to='blog.Tag')),
            ],
        ),
    ]
