# Generated by Django 3.2.9 on 2021-11-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['fecha']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='fecha_publicacion',
        ),
        migrations.AddField(
            model_name='post',
            name='fecha',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog.Tag'),
        ),
    ]
