# Generated by Django 3.2.9 on 2021-12-03 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_autor_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='publicado',
        ),
    ]
