# Generated by Django 3.2.9 on 2021-11-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('texto', models.TextField()),
                ('resumen', models.CharField(max_length=200)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('publicado', models.BooleanField(default=False)),
                ('tags', models.ManyToManyField(blank=True, to='blog.Tag')),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
