# Generated by Django 3.2.9 on 2021-11-24 18:34

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_articulo_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='texto',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
