# Generated by Django 3.2.9 on 2021-11-25 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_articulo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
