# Generated by Django 3.2.9 on 2021-11-25 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_articulo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='resumen',
            field=models.TextField(max_length=200),
        ),
    ]
