# Generated by Django 3.2.9 on 2021-11-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_alter_especialidad_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidad',
            name='text',
            field=models.TextField(),
        ),
    ]
