# Generated by Django 3.2.9 on 2021-11-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_alter_especialidad_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialidad',
            name='alt_img_ca',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='especialidad',
            name='alt_img_es',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='especialidad',
            name='description_ca',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='especialidad',
            name='description_es',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='especialidad',
            name='slug_ca',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='especialidad',
            name='slug_es',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='especialidad',
            name='text_ca',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='especialidad',
            name='text_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='especialidad',
            name='title_ca',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='especialidad',
            name='title_es',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
