# Generated by Django 3.2.9 on 2021-12-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20211128_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialidad',
            name='meta_description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='especialidad',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
