# Generated by Django 3.2.9 on 2021-12-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20211203_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialidad',
            name='meta_description_ca',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='especialidad',
            name='meta_description_es',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='especialidad',
            name='meta_title_ca',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='especialidad',
            name='meta_title_es',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
