# Generated by Django 3.2.9 on 2021-12-13 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_auto_20211203_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidad',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='especialidades'),
        ),
    ]
